blank_issues_enabled: false
contact_links:
  - name: ‚ùì Start a discussion
    url: https://github.com/orgs/atos-actions/discussions
    about: Start a discussion or ask questions about EVIDEN Actions
